# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: version
  type: string
  default: []

steps:
- checkout: none
- ${{ if eq(length(parameters.version), 0) }}:
  - script: echo Foo is empty
    displayName: Foo is empty

- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script:
    echo Add other tasks to build, test, and deploy your project '$(VERSION)'.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

