#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks:
  - name: Pull artifact from S3
    command: "aws s3 cp s3://ramanjulareddy/webapp.war /tmp" 
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: iwayq
      build:
        path: /root/apps/pipeline-project
        pull: no
        args:
          listen_port: 8080
      source: build
  - name: Log into DockerHub
    docker_login:
     username: mhrreddy
     password: Ictl@20


  - name: Push to docker hub
    docker_image:
      name: iwayq
      repository: mhrreddy/iwayq:webapp
      push: yes
      source: local

